# Generated by Django 4.0.4 on 2023-01-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Наименование потребилетя')),
                ('customer_type', models.CharField(max_length=160, verbose_name='Тип потребителя')),
                ('customer_address', models.CharField(max_length=160, verbose_name='Адрес потребителя')),
                ('power', models.FloatField(default=0, verbose_name='Мощность')),
                ('heat_supply', models.BooleanField(default=False, verbose_name='Наличие отопления')),
                ('hot_water', models.BooleanField(default=False, verbose_name='Наличие ГВС')),
                ('people', models.IntegerField(default=0, verbose_name='Кол-во абонентов')),
                ('location', models.CharField(max_length=160, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Потребитель',
                'verbose_name_plural': 'Потребители',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Наименование объекта')),
                ('object_type', models.CharField(max_length=160, verbose_name='Тип объекта')),
                ('plan', models.FileField(blank=True, null=True, upload_to='uploads/plans/')),
                ('boilers', models.IntegerField(default=0, verbose_name='Кол-во котлов')),
                ('power', models.FloatField(default=0, verbose_name='Мощность')),
                ('pumps', models.IntegerField(default=0, verbose_name='Кол-во насосов')),
                ('faucet', models.BooleanField(default=False, verbose_name='Наличие запорной арматуры')),
                ('meters', models.IntegerField(default=0, verbose_name='Площадь')),
                ('people', models.IntegerField(default=0, verbose_name='Кол-во людей')),
                ('location', models.CharField(max_length=160, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=160, verbose_name='Местоположение начала')),
                ('destination_location', models.CharField(max_length=160, verbose_name='Местоположение окончания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.customer')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='connect_objects',
            field=models.ManyToManyField(through='objects.Pipe', to='objects.object'),
        ),
        migrations.AddField(
            model_name='customer',
            name='objects',
            field=models.ManyToManyField(through='objects.Pipe', to='objects.object'),
        ),
    ]
