# Generated by Django 4.0.4 on 2023-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipe',
            options={'verbose_name': 'Труба', 'verbose_name_plural': 'Трубы'},
        ),
        migrations.AddField(
            model_name='pipe',
            name='diameter',
            field=models.IntegerField(default=0, verbose_name='Диаметр'),
        ),
    ]
