# Generated by Django 4.0.4 on 2023-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_pipe_options_pipe_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='object_address',
            field=models.CharField(default=0, max_length=160, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(default=0, max_length=160, verbose_name='Адрес потребителя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(default=0, max_length=160, verbose_name='Тип потребителя'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(default=0, max_length=160, verbose_name='Тип объекта'),
        ),
    ]
