# Generated by Django 4.0.4 on 2023-01-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_objecttype_customertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertype',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='objecttype',
            name='object',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.customertype'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objecttype'),
        ),
    ]
