# Generated by Django 4.0.4 on 2023-01-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_customer_people_alter_customer_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='objects',
        ),
        migrations.RemoveField(
            model_name='object',
            name='connect_objects',
        ),
        migrations.DeleteModel(
            name='Pipe',
        ),
    ]
